
#login
POST http://localhost:8000/api/auth/rest/login/
Content-Type: application/json


{
  "email":"bob@gmail.com",
  "password":"T624183.bob"
}

###

#sign up
POST http://localhost:8000/api/auth/rest/register/
Content-Type: application/json

{
  "email":"bob1@gmail.com",
  "password1":"T624183.bob",
  "password2":"T624183.bob",
  "first_name":"bob",
  "last_name":"mwale"
}

###

#Getting a new access token
GET  http://localhost:8000/api/auth/rest/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA4NDE5Njc5LCJpYXQiOjE3MDg0MTkzNzksImp0aSI6IjhhMTZlMjhjZWI3NTQ3MjE5NzdiNWE3ZjZmNDQ4MTc3IiwidXNlcl9pZCI6Mn0.m-khbEze5aE6SwbPfkyaULnXQjXpKWiDSqd3tV74-cg

###


#Getting a new refresh token
POST  http://localhost:8000/api/auth/rest/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcwODQzMDU5OSwiaWF0IjoxNzA4NDE5Nzk5LCJqdGkiOiJhMjg5NWI5MGI2NzY0NTUwYmU0Y2ZiMmUxNzMzMTkxZCIsInVzZXJfaWQiOjJ9.9mFPMeD1I60GqTx9Jr5f4Fgnf0VZ5szzI_ec2tPgcMk"
}
###


POST http://localhost:8000/api/auth/google/
Content-Type: application/json
"Token": code 4/0AeaYSHB7gXuA1rKiDVyKSMfqmkFZyNzyYhrhnr7pzwUlZSk3H4kDLbwklZmIo4BKLQE-yQ

