
#login
POST http://localhost:8000/api/auth/rest/login/
Content-Type: application/json


{
  "email":"bob@gmail.com",
  "password":"T624183.bob"
}

###

#sign up
POST http://localhost:8000/api/auth/rest/register/
Content-Type: application/json

{
  "email":"bob1@gmail.com",
  "password1":"T624183.bob",
  "password2":"T624183.bob",
  "first_name":"bob",
  "last_name":"mwale"
}

###

#Getting a new access token
GET  http://localhost:8000/api/auth/rest/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA4NDMyMjk0LCJpYXQiOjE3MDg0MzE5OTQsImp0aSI6ImViZTkxOGRkZTZhNjQ4Nzc5NWFiNWNiMjk1MmQzM2E1IiwidXNlcl9pZCI6NX0.GJE0sPSDT0QUEnWsR6oKtjAo69sIlkCKhtldLq55Mvs

###


#Getting a new refresh token
POST  http://localhost:8000/api/auth/rest/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcwODQzMDU5OSwiaWF0IjoxNzA4NDE5Nzk5LCJqdGkiOiJhMjg5NWI5MGI2NzY0NTUwYmU0Y2ZiMmUxNzMzMTkxZCIsInVzZXJfaWQiOjJ9.9mFPMeD1I60GqTx9Jr5f4Fgnf0VZ5szzI_ec2tPgcMk"
}
###


POST http://localhost:8000/api/auth/facebook/
Content-Type: application/json

{
  "provider":"facebook",
  "access_token":"EAAUOt3abGmcBO85foc6xpeT13vy5OVtCLT5lQRSUiq0cdCmMIQp76vAiOL8Gn8fxZCvXkKBAUdIMjkhRXu22jqJEBUDou3TFxBhHPZCoMbrU8KDHHYcvPgLN9jGwA7QTgHYF2qEgj8IW6qGry8t6DyU6MtKoxvdMsVk50KJmVSOoHBatSnKCZBE7wrB2IjQpQZDZD"
}

##



